<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>无用小网站</title>
</head>
<body>
    <p><a href="https://github.com/EGO-Zxj01">👉点击这里👈</a></p>

    <p>什么都没有</p>
    <p>什么都没有</p>
    <p>什么都没有</p>
    <p>什么都没有</p>
    <p>什么都没有</p>
    <p>什么都没有</p>
    <p>什么都没有</p>
    <p>什么都没有</p>
    <p>什么都没有</p>
    <p>乐</p>
</body>
</html>
